---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: set current github commit as version when available
      ansible.builtin.set_fact:
        paperlessng_version: "{{ lookup('env', 'TARGET_GITHUB_SHA') | default('master', True) }}"
    - name: "Include paperless.ngx"
      ansible.builtin.include_role:
        name: "paperless.ngx"
