---
- name: install previous release
  hosts: all
  tasks:
    - name: set previous version as installation target
      ansible.builtin.set_fact:
        paperlessng_version: latest

    - name: install previous paperless-ngx release
      ansible.builtin.include_role:
        name: "paperless.ngx"
