---
name: Molecule Test
on: [push, pull_request]
jobs:
  molecule:
    runs-on: ubuntu-latest
    name: Molecule Test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install pipenv
        run: pipx install pipenv
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pipenv"
          cache-dependency-path: 'Pipfile.lock'
      -
        name: Install Python dependencies
        run: |
          pipenv sync --dev
      -
        name: Test with molecule
        run: |
          pipenv run molecule test